apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: challenge-05
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: challenge-05
  creationTimestamp: null
  labels:
    app: python-ms-deployment
  name: python-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-ms-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-ms-deployment
    spec:
      containers:
      - image: prajwal3498/python-ms-crisp-devops:latest
        name: python-ms-crisp-devops
        resources:
          requests:
            memory: "30Mi"
          limits:
            memory: "30Mi"
        envFrom:
        - configMapRef:
            name: my-configmap
        - secretRef:
            name: my-secret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: challenge-05
  creationTimestamp: null
  labels:
    app: python-ms-deployment
  name: python-ms-svc
spec:
  ports:
  - port: 777
    protocol: TCP
    targetPort: 7777
  selector:
    app: python-ms-deployment
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
data:
  challenge: "3"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: my-configmap
  namespace: challenge-05
---
apiVersion: v1
data:
  password: SGVsbG8xMjM=
kind: Secret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: challenge-05