apiVersion: v1
kind: Service
metadata:
  namespace: challenge-01
  creationTimestamp: null
  labels:
    app: python-ms-deployment
  name: python-ms-svc
spec:
  ports:
  - port: 777
    protocol: TCP
    targetPort: 7777
  selector:
    app: python-ms-deployment
  type: NodePort
status:
  loadBalancer: {}